services:
  db:
    image: postgres:16
    container_name: cert_db
    environment:
      POSTGRES_USER: cert_user
      POSTGRES_PASSWORD: cert_pass
      POSTGRES_DB: certdb
    ports:
      - "5432:5432"
    volumes:
      - cert_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    container_name: cert_api
    environment:
      DATABASE_URL: postgresql://cert_user:cert_pass@db:5432/certdb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: cert_frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  cert_pgdata:
